/**
 * Default Local-dev configuration template.
 * Real environment.ts will be generated by script at build time 
 * and placeholder/s replace from shared infra .env  
 */
export const environment = {
    production: false,
    name: "local-dev",
    apiUrl: "__API_BASE_URL__"    
 };
