/**
 * Default Local-dev configuration template.
 * Real environment.ts will be generated by script at build time 
 * and placeholder/s replace from shared infra .env  
 */
export const environment = {
    apiBaseUrl: 'http://localhost:8083'   
 };
