version: "3.9"

services:
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devdb
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
    depends_on:
      - db
    volumes:
      - ../../logs/api:/logs
    networks:
      - dev-local

  db:
    image: postgres:15
    container_name: db-dev-local
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5433:5432"     # For debugging only
    volumes:
      - local-db-data:/var/lib/postgresql/data
    networks:
      - dev-local
      - dev-tools

volumes:
  local-db-data:

networks:
  dev-local:
    external: false
  dev-tools:
    external: true
