version: "3.9"

services:
  api:
    container_name: api-local-dev
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.local
    ports:
      - "${SERVICE_PORT}:8080"  
    env_file:
      - ../runtime/env/local.env
    depends_on:
      - db
    volumes:
      - ../../logs/dev/docker:/logs
    networks:
      - dev-local

  db:
    container_name: db-local-dev
    image: postgres:15  
    env_file:
      - ../runtime/env/local.env
    ports:
      - "${POSTGRES_PORT}:5432"     # For debugging only
    volumes:
      - local-db-data:/var/lib/postgresql/data
    networks:
      - dev-local
      - dev-tools

volumes:
  local-db-data:

networks:
  dev-local:
    external: false
  dev-tools:
    external: true
