# =================================================================
# Local dev profile overrides
# =================================================================
spring:
  config:
    activate:
      on-profile: local

# =================================================================
# Logging configuration
# =================================================================
logging:
  level:
    root: DEBUG
    com.example.api: DEBUG