services:
  api:
    container_name: api-dev
    ports:
      - "8082:8080"
    env_file:
      - ../env/dev.env

  db:
    container_name: db-dev
    env_file:
      - ../env/dev.env
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - dev-tools

volumes:
  dev-db-data:

networks:
  dev-tools: 
    external: true
      
      
