version: "3.9"

services:
  api:
    image: idevon90/api:latest
    container_name: api-dev
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devdb
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
    depends_on:
      - db
    networks:
      - dev-env

  db:
    image: postgres:15
    container_name: db-dev
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - dev-env
      - dev-tools

volumes:
  dev-db-data:

networks:
  dev-env:
    external: false
  dev-tools: 
    external: true
      
      
