services:
  api: 
    image: idevon90/api:${IMAGE_TAG}
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:18
    networks:
      - app-net

networks:
  app-net:
    driver: bridge