name: CI

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  validate-build-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Validate repo structure
      - name: Validate repository structure
        run: |
          test -d apps
          test -d infra
          test -d docs

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build Spring boot JAR
      - name: Build JAR
        run: |
          cd apps/api
          mvn clean package -DskipTests

      # Run Tests
      - name: Run Tests
        run: |
          cd apps/api
          mvn test

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            -t ${{secrets.DOCKERHUB_USERNAME}}/api:${{github.sha}} \
            -t ${{secrets.DOCKERHUB_USERNAME}}/api:ci-latest \
            ./apps/api

      # Push Docker Image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/api:${{github.sha}}
          docker push ${{secrets.DOCKERHUB_USERNAME}}/api:ci-latest
